# Generated by Django 5.2.14 on 2026-05-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_loja_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['esgotado', 'ordem', '-destaque', '-criado_em'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddField(
            model_name='loja',
            name='plano',
            field=models.CharField(choices=[('gratis', 'Gratis'), ('premium', 'Premium')], default='gratis', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='cliques_whatsapp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
