# Generated by Django 5.2.14 on 2026-05-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_produto_options_loja_plano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='tema',
            field=models.CharField(choices=[('elegante', 'Elegante'), ('minimalista', 'Minimalista'), ('boutique', 'Boutique'), ('streetwear', 'Streetwear')], default='elegante', max_length=20),
        ),
    ]
