# Generated by Django 5.2.14 on 2026-05-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_loja_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='banner_imagem',
            field=models.ImageField(blank=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='loja',
            name='banner_texto',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='loja',
            name='banner_titulo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_antigo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
    ]
