# Generated by Django 5.2.14 on 2026-05-23 04:29

from django.db import migrations, models


def converter_lojas_para_premium(apps, schema_editor):
    Loja = apps.get_model("loja", "Loja")
    Loja.objects.exclude(plano="premium").update(plano="premium")


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_lead'),
    ]

    operations = [
        migrations.RunPython(converter_lojas_para_premium, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='loja',
            name='plano',
            field=models.CharField(choices=[('premium', 'Premium')], default='premium', max_length=20),
        ),
    ]
