# Generated by Django 5.2.14 on 2026-05-24 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_alter_loja_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='cliente_nome',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='cliente_telefone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('atendimento', 'Em atendimento'), ('concluido', 'Concluido')], default='novo', max_length=20),
        ),
        migrations.AddField(
            model_name='loja',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/'),
        ),
        migrations.CreateModel(
            name='ProdutoVariacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=80)),
                ('tamanho', models.CharField(max_length=40)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('disponivel', models.BooleanField(default=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='loja.produto')),
            ],
            options={
                'verbose_name': 'Variacao do produto',
                'verbose_name_plural': 'Variacoes do produto',
                'ordering': ['cor', 'tamanho'],
                'unique_together': {('produto', 'cor', 'tamanho')},
            },
        ),
    ]
