# Generated by Django 5.2.14 on 2026-05-24 20:44

import loja.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_lead_cliente_nome_lead_cliente_telefone_lead_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='assinatura_ativa_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='assinatura_cancelada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='assinatura_status',
            field=models.CharField(choices=[('trial', 'Teste gratis'), ('ativa', 'Ativa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='loja',
            name='pagamento_referencia',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='loja',
            name='trial_termina_em',
            field=models.DateTimeField(blank=True, default=loja.models.trial_padrao, null=True),
        ),
    ]
