# Generated by Django 5.2.14 on 2026-05-24 20:56

import django.db.models.deletion
import loja.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_loja_assinatura_ativa_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(choices=[('mercado_pago', 'Mercado Pago')], default='mercado_pago', max_length=30)),
                ('status', models.CharField(choices=[('criado', 'Criado'), ('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('cancelado', 'Cancelado')], default='criado', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('39.90'), max_digits=8)),
                ('external_reference', models.CharField(default=loja.models.pagamento_referencia_padrao, max_length=80, unique=True)),
                ('preference_id', models.CharField(blank=True, max_length=120)),
                ('init_point', models.URLField(blank=True)),
                ('sandbox_init_point', models.URLField(blank=True)),
                ('payment_id', models.CharField(blank=True, max_length=120)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='loja.loja')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
