# Generated by Django 5.2.14 on 2026-05-24 22:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def criar_cupom_lancamento(apps, schema_editor):
    Cupom = apps.get_model("loja", "Cupom")
    Cupom.objects.get_or_create(
        codigo="MODALINK10",
        defaults={"percentual_desconto": 10, "ativo": True},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0012_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('percentual_desconto', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cupom',
                'verbose_name_plural': 'Cupons',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='dominio_personalizado',
            field=models.CharField(blank=True, help_text='Ex.: catalogo.sualoja.com.br', max_length=120),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='valor_final',
            field=models.DecimalField(decimal_places=2, default=Decimal('39.90'), max_digits=8),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='cupom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.cupom'),
        ),
        migrations.RunPython(criar_cupom_lancamento, migrations.RunPython.noop),
    ]
