# Generated by Django 5.2.14 on 2026-06-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0014_cupom_vestlink10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='assinatura_status',
            field=models.CharField(choices=[('trial', 'Teste grátis'), ('ativa', 'Ativa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='trial', max_length=20),
        ),
    ]
