# Generated by Django 5.2.15 on 2026-06-09 02:01

import loja.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0017_vendedor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='endereco_completo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='tipo_entrega',
            field=models.CharField(blank=True, choices=[('retirada', 'Retirada na Loja'), ('entrega', 'Entrega a Domicílio')], default='retirada', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Pendente (Novo)'), ('atendimento', 'Pendente (Em atendimento)'), ('concluido', 'Concluído')], default='novo', max_length=20),
        ),
        migrations.AlterField(
            model_name='loja',
            name='telefone',
            field=models.CharField(help_text='Somente números com DDD.', max_length=20, validators=[loja.validators.validar_whatsapp]),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, validators=[loja.validators.validar_whatsapp]),
        ),
    ]
