# Generated by Django 5.2.14 on 2026-06-16 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0018_lead_endereco_completo_lead_tipo_entrega_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='anonimizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AceiteLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termos_versao', models.CharField(max_length=20)),
                ('privacidade_versao', models.CharField(max_length=20)),
                ('fonte', models.CharField(blank=True, max_length=40)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('navegador', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceites_legais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aceite legal',
                'verbose_name_plural': 'Aceites legais',
                'ordering': ['-criado_em'],
            },
        ),
    ]
